"""atualizaçao 6

Revision ID: 03ee8006abe9
Revises: 2014ac3e229c
Create Date: 2022-05-09 22:33:27.307988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ee8006abe9'
down_revision = '2014ac3e229c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Categorias', sa.String(length=100), nullable=True))
        batch_op.drop_column('Categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Categoria', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('Categorias')

    # ### end Alembic commands ###
