"""fixing the migration

Revision ID: 104b61104e07
Revises: 
Create Date: 2022-03-29 00:03:13.460568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104b61104e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('nome_completo', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('nome', name=op.f('uq_usuario_nome'))
    )
    op.create_table('conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_a_id', sa.Integer(), nullable=False),
    sa.Column('part_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_a_id'], ['usuario.id'], name=op.f('fk_conversa_part_a_id_usuario')),
    sa.ForeignKeyConstraint(['part_b_id'], ['usuario.id'], name=op.f('fk_conversa_part_b_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversa'))
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=144), nullable=False),
    sa.Column('remetente', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name=op.f('fk_mensagem_conversa_id_conversa')),
    sa.ForeignKeyConstraint(['remetente'], ['usuario.id'], name=op.f('fk_mensagem_remetente_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('conversa')
    op.drop_table('usuario')
    # ### end Alembic commands ###
