"""imagem

Revision ID: 146b53312922
Revises: 5fea82f61035
Create Date: 2022-06-09 22:41:09.171332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146b53312922'
down_revision = '5fea82f61035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_prato', sa.String(length=100), nullable=True))

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_perfil', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('imagem_perfil')

    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.drop_column('imagem_prato')

    # ### end Alembic commands ###
