"""mudança coluna Valor

Revision ID: 1b3539da7ac9
Revises: 330a47212977
Create Date: 2022-05-14 20:33:35.264351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3539da7ac9'
down_revision = '330a47212977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Valor do prato', sa.String(length=10), nullable=False))
        batch_op.drop_column('Valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Valor', sa.FLOAT(), nullable=False))
        batch_op.drop_column('Valor do prato')

    # ### end Alembic commands ###
