"""atualizaçao 4

Revision ID: 2014ac3e229c
Revises: 99c31f107b79
Create Date: 2022-05-09 22:31:47.495229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2014ac3e229c'
down_revision = '99c31f107b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('término de funcionamento', sa.DateTime(), nullable=False))
        batch_op.drop_column('funcionamento_termino')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcionamento_termino', sa.DATETIME(), nullable=False))
        batch_op.drop_column('término de funcionamento')

    # ### end Alembic commands ###
