"""Tabela Cliente

Revision ID: 22a1b3d9d937
Revises: 104b61104e07
Create Date: 2022-04-20 00:01:07.231861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a1b3d9d937'
down_revision = '104b61104e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversa')
    op.drop_table('mensagem')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=30), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_usuario'),
    sa.UniqueConstraint('nome', name='uq_usuario_nome')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.VARCHAR(length=144), nullable=False),
    sa.Column('remetente', sa.INTEGER(), nullable=False),
    sa.Column('conversa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name='fk_mensagem_conversa_id_conversa'),
    sa.ForeignKeyConstraint(['remetente'], ['usuario.id'], name='fk_mensagem_remetente_usuario'),
    sa.PrimaryKeyConstraint('id', name='pk_mensagem')
    )
    op.create_table('conversa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_a_id', sa.INTEGER(), nullable=False),
    sa.Column('part_b_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['part_a_id'], ['usuario.id'], name='fk_conversa_part_a_id_usuario'),
    sa.ForeignKeyConstraint(['part_b_id'], ['usuario.id'], name='fk_conversa_part_b_id_usuario'),
    sa.PrimaryKeyConstraint('id', name='pk_conversa')
    )
    # ### end Alembic commands ###
