"""Tabela Cardápio

Revision ID: 330a47212977
Revises: b0b81e027502
Create Date: 2022-05-14 19:54:42.301201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330a47212977'
down_revision = 'b0b81e027502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome do prato', sa.String(length=400), nullable=False),
    sa.Column('Valor', sa.Float(), nullable=False),
    sa.Column('Ingredientes', sa.String(length=500), nullable=False),
    sa.Column('Tempo de preparo', sa.String(length=6), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], name=op.f('fk_cardapio_restaurante_id_restaurante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardapio'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardapio')
    # ### end Alembic commands ###
