"""Adicionada a tabela mensagem

Revision ID: 55cd26f65bef
Revises: ea7901a05c3d
Create Date: 2022-03-16 19:16:43.954874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cd26f65bef'
down_revision = 'ea7901a05c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=144), nullable=False),
    sa.Column('remetente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['remetente'], ['usuario.id'], name=op.f('fk_mensagem_remetente_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    # ### end Alembic commands ###
