"""Conversas

Revision ID: 570809155ba1
Revises: 55cd26f65bef
Create Date: 2022-03-16 19:47:29.268158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570809155ba1'
down_revision = '55cd26f65bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mensagem')
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mensagem_conversa_id_conversa'), 'conversa', ['conversa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mensagem_conversa_id_conversa'), type_='foreignkey')
        batch_op.drop_column('conversa_id')

    op.create_table('_alembic_tmp_mensagem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.VARCHAR(length=144), nullable=False),
    sa.Column('remetente', sa.INTEGER(), nullable=False),
    sa.Column('conversa_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name='fk_mensagem_conversa_id_conversa'),
    sa.ForeignKeyConstraint(['remetente'], ['usuario.id'], name='fk_mensagem_remetente_usuario'),
    sa.PrimaryKeyConstraint('id', name='pk_mensagem')
    )
    # ### end Alembic commands ###
