"""add coluna endereco

Revision ID: 5fea82f61035
Revises: 9b7ff5dfdb50
Create Date: 2022-05-31 23:45:03.836062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fea82f61035'
down_revision = '9b7ff5dfdb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidofeito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Endereço', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidofeito', schema=None) as batch_op:
        batch_op.drop_column('Endereço')

    # ### end Alembic commands ###
