"""cliente pediu nome

Revision ID: 6217955ba83c
Revises: ffd0ff6100b6
Create Date: 2022-06-20 13:37:11.019182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6217955ba83c'
down_revision = 'ffd0ff6100b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidofeito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nome do cliente', sa.String(length=400), nullable=True))
        batch_op.drop_column('Cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidofeito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cliente', sa.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('Nome do cliente')

    # ### end Alembic commands ###
