"""Atualizacao 2

Revision ID: 71c7aef9b005
Revises: 3d085d04ee33
Create Date: 2022-05-07 14:16:51.554980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c7aef9b005'
down_revision = '3d085d04ee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Endereço', sa.String(length=200), nullable=True))

    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.drop_column('Telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Telefone', sa.VARCHAR(length=11), nullable=False))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('Endereço')

    # ### end Alembic commands ###
