"""boolean > string

Revision ID: 8010377d21c2
Revises: 433da0a99065
Create Date: 2022-05-09 22:18:32.819003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8010377d21c2'
down_revision = '433da0a99065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Veículo', sa.String(length=100), nullable=True))
        batch_op.drop_column('Veiculo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Veiculo', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('Veículo')

    # ### end Alembic commands ###
