"""acento add

Revision ID: 88205260b8c2
Revises: 8010377d21c2
Create Date: 2022-05-09 22:21:44.670519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88205260b8c2'
down_revision = '8010377d21c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Região', sa.String(length=100), nullable=True))
        batch_op.drop_column('Regiao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Regiao', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('Região')

    # ### end Alembic commands ###
