"""atualizaçao 3

Revision ID: 99c31f107b79
Revises: 88205260b8c2
Create Date: 2022-05-09 22:29:08.848008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c31f107b79'
down_revision = '88205260b8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cidade ', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('início de funcionamento', sa.DateTime(), nullable=False))
        batch_op.drop_column('Cidade')
        batch_op.drop_column('funcionamento_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcionamento_inicio', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('Cidade', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('início de funcionamento')
        batch_op.drop_column('Cidade ')

    # ### end Alembic commands ###
