"""tabela pedidofeito

Revision ID: 9b7ff5dfdb50
Revises: 1b3539da7ac9
Create Date: 2022-05-29 00:47:16.871150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7ff5dfdb50'
down_revision = '1b3539da7ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidofeito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome do pedido', sa.String(length=400), nullable=False),
    sa.Column('Valor do pedido', sa.String(length=10), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_pedidofeito_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], name=op.f('fk_pedidofeito_restaurante_id_restaurante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidofeito'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidofeito')
    # ### end Alembic commands ###
