"""nome_restaurante

Revision ID: ae1d9ac1e89e
Revises: da34ce736b11
Create Date: 2022-06-12 18:22:03.832370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d9ac1e89e'
down_revision = 'da34ce736b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nome do restaurante', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.drop_column('Nome do restaurante')

    # ### end Alembic commands ###
