"""atualizaçao 8

Revision ID: b0b81e027502
Revises: 03ee8006abe9
Create Date: 2022-05-09 22:45:12.632180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b81e027502'
down_revision = '03ee8006abe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Abre:', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('Fecha:', sa.String(length=6), nullable=False))
        batch_op.drop_column('início de funcionamento')
        batch_op.drop_column('término de funcionamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('término de funcionamento', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('início de funcionamento', sa.DATETIME(), nullable=False))
        batch_op.drop_column('Fecha:')
        batch_op.drop_column('Abre:')

    # ### end Alembic commands ###
