"""cardapio

Revision ID: b851eba2ea95
Revises: ae1d9ac1e89e
Create Date: 2022-06-13 00:14:13.947075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b851eba2ea95'
down_revision = 'ae1d9ac1e89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome do prato', sa.String(length=400), nullable=False),
    sa.Column('Valor do prato', sa.String(length=10), nullable=False),
    sa.Column('imagem_prato', sa.String(length=100), nullable=True),
    sa.Column('Ingredientes', sa.String(length=500), nullable=False),
    sa.Column('Tempo de preparo', sa.String(length=6), nullable=False),
    sa.Column('Restaurante_adicionou', sa.String(length=400), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], name=op.f('fk_cardapio_restaurante_id_restaurante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardapio'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardapio')
    # ### end Alembic commands ###
