"""cardapio categoria

Revision ID: d31510fa0db3
Revises: b851eba2ea95
Create Date: 2022-06-13 00:27:06.163743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31510fa0db3'
down_revision = 'b851eba2ea95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Categorias', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardapio', schema=None) as batch_op:
        batch_op.drop_column('Categorias')

    # ### end Alembic commands ###
