"""imagem cliente

Revision ID: da34ce736b11
Revises: 146b53312922
Create Date: 2022-06-09 22:46:19.167355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da34ce736b11'
down_revision = '146b53312922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_perfil', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('imagem_perfil')

    # ### end Alembic commands ###
