"""Tabela Entregador

Revision ID: dbc464232a60
Revises: e6b4f8aad656
Create Date: 2022-04-27 22:21:04.738359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbc464232a60"
down_revision = "e6b4f8aad656"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Nome", sa.String(length=400), nullable=False),
        sa.Column("Email", sa.String(length=100), nullable=False),
        sa.Column("Senha", sa.String(length=100), nullable=False),
        sa.Column("Endereço", sa.String(length=200), nullable=False),
        sa.Column("Cidade", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restaurante")),
        sa.UniqueConstraint("Email", name=op.f("uq_restaurante_Email")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurante")
    # ### end Alembic commands ###
